In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import seaborn as sns 

import itertools

import scipy

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
df = pd.read_csv(r"C:\Users\lu_xi\OneDrive\Queens MMA\823 Analytics for Financial Markets\Course Project\Data\clean_data.csv")
# df_train = pd.read_csv(r"C:\Users\lu_xi\OneDrive\Queens MMA\823 Analytics for Financial Markets\Course Project\Data\new_train.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32950 entries, 0 to 32949
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    32950 non-null  int64
 1   age           32950 non-null  object
 2   job           32950 non-null  object
 3   marital       32950 non-null  object
 4   education     32950 non-null  object
 5   default       32950 non-null  object
 6   housing       32950 non-null  object
 7   loan          32950 non-null  object
 8   contact       32950 non-null  object
 9   month         32950 non-null  object
 10  duration      32950 non-null  float64
 11  campaign      32950 non-null  int64
 12  previous      32950 non-null  int64
 13  poutcome      32950 non-null  object
 14  y             32950 non-null  int64
 15  duration_min  32950 non-null  float64
 16  campaign1     32950 non-null  bool
 17  student       32950 non-null  bool
 18  retired       32950 non-null  bool
dtypes: bool(3), float64(2), int64(4), object(10)
memory usage: 4.1+ MB

In [3]:
df.head(3)

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,month,duration,campaign,previous,poutcome,y,duration_min,campaign1,student,retired
0,1,41-50,blue-collar,married,basic.9y,unknown,no,no,cellular,Q4,1.565138,4,0,nonexistent,0,3.783333,False,False,False
1,2,31-40,entrepreneur,married,university.degree,no,no,no,telephone,Q4,1.474000,2,1,failure,0,3.366667,False,False,False
2,3,>60,retired,married,basic.4y,no,no,no,cellular,Q3,3.002377,1,0,nonexistent,1,19.133333,True,False,True

In [4]:
from sklearn.model_selection import train_test_split

X = df.drop(['y'], axis=1)
y = df['y']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=7)

In [5]:
y_train.value_counts()
y_test.value_counts()

0    23390
1     2970
Name: y, dtype: int64

0    5848
1     742
Name: y, dtype: int64

In [6]:
from pycaret.classification import *

In [7]:
#intialize the setup
exp_clf = setup(df, target = 'y', session_id = 123)

In [8]:
best_model = compare_models()

In [9]:
print(best_model)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=123, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [10]:
predict_model(best_model);

In [11]:
final_model = finalize_model(best_model)

FLAML Try-out

In [29]:
# ! pip install flaml

In [19]:
# pip install flaml

In [21]:
from flaml import AutoML
automl = AutoML()
automl.fit(X_train, y_train, task="classification")

ImportError: cannot import name 'mean_absolute_percentage_error' from 'sklearn.metrics' (C:\Users\lu_xi\anaconda3\envs\mma\lib\site-packages\sklearn\metrics\__init__.py)

In [31]:
python -c "import sklearn; sklearn.show_versions()"

SyntaxError: invalid syntax (<ipython-input-31-f1e9ceca1d5c>, line 1)

In [33]:
import sklearn

In [36]:
sklearn.show_versions()

System:
    python: 3.8.11 (default, Aug  6 2021, 09:57:55) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\lu_xi\anaconda3\envs\mma\python.exe
   machine: Windows-10-10.0.19043-SP0

Python dependencies:
          pip: 21.0.1
   setuptools: 52.0.0.post20210125
      sklearn: 0.23.2
        numpy: 1.19.5
        scipy: 1.5.4
       Cython: 0.29.14
       pandas: 1.3.2
   matplotlib: 3.4.3
       joblib: 1.0.1
threadpoolctl: 2.2.0

Built with OpenMP: True

In [35]:
pip install -U scikit-learn

Requirement already satisfied: scikit-learn in c:\users\lu_xi\anaconda3\envs\mma\lib\site-packages (1.0)Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: joblib>=0.11 in c:\users\lu_xi\anaconda3\envs\mma\lib\site-packages (from scikit-learn) (1.0.1)
Requirement already satisfied: numpy>=1.14.6 in c:\users\lu_xi\anaconda3\envs\mma\lib\site-packages (from scikit-learn) (1.19.5)
Requirement already satisfied: scipy>=1.1.0 in c:\users\lu_xi\anaconda3\envs\mma\lib\site-packages (from scikit-learn) (1.5.4)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\lu_xi\anaconda3\envs\mma\lib\site-packages (from scikit-learn) (2.2.0)

In [30]:
from sklearn.utils import check_arrays
def mean_absolute_percentage_error(y_true, y_pred): 
    y_true, y_pred = check_arrays(y_true, y_pred)

    ## Note: does not handle mix 1d representation
    #if _is_1d(y_true): 
    #    y_true, y_pred = _check_1d_array(y_true, y_pred)

    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

ImportError: cannot import name 'check_arrays' from 'sklearn.utils' (C:\Users\lu_xi\anaconda3\envs\mma\lib\site-packages\sklearn\utils\__init__.py)

In [28]:
! pip install numpy scipy cython
! pip install --verbose --no-build-isolation --editable .

Requirement already satisfied: numpy in c:\users\lu_xi\anaconda3\envs\mma\lib\site-packages (1.19.5)
Requirement already satisfied: scipy in c:\users\lu_xi\anaconda3\envs\mma\lib\site-packages (1.5.4)
Requirement already satisfied: cython in c:\users\lu_xi\anaconda3\envs\mma\lib\site-packages (0.29.14)
Using pip 21.0.1 from C:\Users\lu_xi\anaconda3\envs\mma\lib\site-packages\pip (python 3.8)

ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: c:\Users\lu_xi\OneDrive\GitRepos\Islington\Study\823_Financial_Analytics

Non-user install because site-packages writeable
Created temporary directory: C:\Users\lu_xi\AppData\Local\Temp\pip-ephem-wheel-cache-24xw1fyu
Created temporary directory: C:\Users\lu_xi\AppData\Local\Temp\pip-req-tracker-4vtf3qob
Initialized build tracking at C:\Users\lu_xi\AppData\Local\Temp\pip-req-tracker-4vtf3qob
Created build tracker: C:\Users\lu_xi\AppData\Local\Temp\pip-req-tracker-4vtf3qob
Entered build tracker: C:\Users\lu_xi\AppData\Local\Temp\pip-req-tracker-4vtf3qob
Created temporary directory: C:\Users\lu_xi\AppData\Local\Temp\pip-install-cov8snr9
Exception information:
Traceback (most recent call last):
  File "C:\Users\lu_xi\anaconda3\envs\mma\lib\site-packages\pip\_internal\cli\base_command.py", line 189, in _main
    status = self.run(options, args)
  File "C:\Users\lu_xi\anaconda3\envs\mma\lib\site-packages\pip\_internal\cli\req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "C:\Users\lu_xi\anaconda3\envs\mma\lib\site-packages\pip\_internal\commands\install.py", line 287, in run
    reqs = self.get_requirements(args, options, finder, session)
  File "C:\Users\lu_xi\anaconda3\envs\mma\lib\site-packages\pip\_internal\cli\req_command.py", line 348, in get_requirements
    req_to_add = install_req_from_editable(
  File "C:\Users\lu_xi\anaconda3\envs\mma\lib\site-packages\pip\_internal\req\constructors.py", line 212, in install_req_from_editable
    parts = parse_req_from_editable(editable_req)
  File "C:\Users\lu_xi\anaconda3\envs\mma\lib\site-packages\pip\_internal\req\constructors.py", line 183, in parse_req_from_editable
    name, url, extras_override = parse_editable(editable_req)
  File "C:\Users\lu_xi\anaconda3\envs\mma\lib\site-packages\pip\_internal\req\constructors.py", line 96, in parse_editable
    raise InstallationError(msg)
pip._internal.exceptions.InstallationError: File "setup.py" not found. Directory cannot be installed in editable mode: c:\Users\lu_xi\OneDrive\GitRepos\Islington\Study\823_Financial_Analytics
Removed build tracker: 'C:\\Users\\lu_xi\\AppData\\Local\\Temp\\pip-req-tracker-4vtf3qob'